In [1]:
import pandas as pd

on_bad_lines {‘error’, ‘warn’, ‘skip’} ou Callable, padrão ‘error’

Especifica o que fazer ao encontrar uma linha inválida (uma linha com campos a mais do que o esperado). Os valores permitidos são:

'error': Levanta uma Exceção (Exception) quando uma linha inválida é encontrada.

'warn': Levanta um aviso (warning) quando uma linha inválida é encontrada e pula (ignora) essa linha.

'skip': Pula as linhas inválidas silenciosamente, sem levantar exceções ou avisos quando são encontradas.

Callable (função chamável): Uma função que processará uma única linha inválida.

Com engine='python': A função deve ter a assinatura (bad_line: list[str]) -> list[str] | None. O parâmetro bad_line é uma lista de strings divididas pelo separador (sep). Se a função retornar None, a linha inválida será ignorada. Se a função retornar uma nova lista de strings com mais elementos do que o esperado, um aviso ParserWarning será emitido e os elementos excedentes serão descartados.

Com engine='pyarrow': A função deve ter a assinatura conforme descrito na documentação do PyArrow: invalid_row_handler.



sepstr, default ‘,’
Character or regex pattern to treat as the delimiter. If sep=None, the C engine cannot automatically detect the separator, but the Python parsing engine can, meaning the latter will be used and automatically detect the separator from only the first valid row of the file by Python’s builtin sniffer tool, csv.Sniffer. In addition, separators longer than 1 character and different from '\s+' will be interpreted as regular expressions and will also force the use of the Python parsing engine. Note that regex delimiters are prone to ignoring quoted data. Regex example: '\r\t'.

In [2]:
#on_bad_lines ignora ou denuncia linhas com erro
df = pd.read_csv("gapminder.csv", on_bad_lines = "skip", sep = ",")

#head limita as linhas
df.head() #mostra apenas as 5 primeiras linhas

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [3]:
#rename renomeia as colunas
df = df.rename(columns={"country": "País", "continent": "Continete", "year": "Ano", "lifeExp": "Expectativa de vida", "pop": "População", "gdpPercap": "PIB"})
df.head()

          País Continete   Ano  Expectativa de vida  População         PIB
0  Afghanistan      Asia  1952               28.801    8425333  779.445314
1  Afghanistan      Asia  1957               30.332    9240934  820.853030
2  Afghanistan      Asia  1962               31.997   10267083  853.100710
3  Afghanistan      Asia  1967               34.020   11537966  836.197138
4  Afghanistan      Asia  1972               36.088   13079460  739.981106

In [4]:
#mostra o tamanho de linhas e colunas
df.shape

(1704, 6)

In [5]:
df.columns #retorna a coluna do conjunto de dados

Index(['País', 'Continete', 'Ano', 'Expectativa de vida', 'População', 'PIB'], dtype='str')

In [6]:
df.dtypes #retorna o tipo de dados de cada

País                       str
Continete                  str
Ano                      int64
Expectativa de vida    float64
População                int64
PIB                    float64
dtype: object

In [7]:
"""
Tail: Cauda, algo que está no fim

A mesma coisa de head, mas pega as últimas linhas
"""

df.tail(15)

          País Continete   Ano  Expectativa de vida  População          PIB
1689    Zambia    Africa  1997               40.238    9417789  1071.353818
1690    Zambia    Africa  2002               39.193   10595811  1071.613938
1691    Zambia    Africa  2007               42.384   11746035  1271.211593
1692  Zimbabwe    Africa  1952               48.451    3080907   406.884115
1693  Zimbabwe    Africa  1957               50.469    3646340   518.764268
1694  Zimbabwe    Africa  1962               52.358    4277736   527.272182
1695  Zimbabwe    Africa  1967               53.995    4995432   569.795071
1696  Zimbabwe    Africa  1972               55.635    5861135   799.362176
1697  Zimbabwe    Africa  1977               57.674    6642107   685.587682
1698  Zimbabwe    Africa  1982               60.363    7636524   788.855041
1699  Zimbabwe    Africa  1987               62.351    9216418   706.157306
1700  Zimbabwe    Africa  1992               60.377   10704340   693.420786
1701  Zimbabwe    Africa  1997               46.809   11404948   792.449960
1702  Zimbabwe    Africa  2002               39.989   11926563   672.038623
1703  Zimbabwe    Africa  2007               43.487   12311143   469.709298

In [8]:
df.describe #estatísticas do conjunto de dados

<bound method NDFrame.describe of              País Continete   Ano  Expectativa de vida  População         PIB
0     Afghanistan      Asia  1952               28.801    8425333  779.445314
1     Afghanistan      Asia  1957               30.332    9240934  820.853030
2     Afghanistan      Asia  1962               31.997   10267083  853.100710
3     Afghanistan      Asia  1967               34.020   11537966  836.197138
4     Afghanistan      Asia  1972               36.088   13079460  739.981106
...           ...       ...   ...                  ...        ...         ...
1699     Zimbabwe    Africa  1987               62.351    9216418  706.157306
1700     Zimbabwe    Africa  1992               60.377   10704340  693.420786
1701     Zimbabwe    Africa  1997               46.809   11404948  792.449960
1702     Zimbabwe    Africa  2002               39.989   11926563  672.038623
1703     Zimbabwe    Africa  2007               43.487   12311143  469.709298

[1704 rows x 6 columns]>

In [9]:
df["Continete"].unique() #apenas valores unicos, da tabela "Continete"

<StringArray>
['Asia', 'Europe', 'Africa', 'Americas', 'Oceania']
Length: 5, dtype: str

In [10]:
Oceania = df.loc[df["Continete"] == "Oceania"] #loc filtra somente Oceania, dentro de Continente

Oceania.head()

         País Continete   Ano  Expectativa de vida  População          PIB
60  Australia   Oceania  1952                69.12    8691212  10039.59564
61  Australia   Oceania  1957                70.33    9712569  10949.64959
62  Australia   Oceania  1962                70.93   10794968  12217.22686
63  Australia   Oceania  1967                71.10   11872264  14526.12465
64  Australia   Oceania  1972                71.93   13177000  16788.62948

In [11]:
Oceania["Continete"].unique()

<StringArray>
['Oceania']
Length: 1, dtype: str

In [12]:
"""
Conta quantos países temos para cada continente

groupby agrupa por continente

nunique faz a contagem de maneira única
"""

df.groupby("Continete")["País"].nunique()

Continete
Africa      52
Americas    25
Asia        33
Europe      30
Oceania      2
Name: País, dtype: int64

In [13]:
#expectativa de vida média por ano
df.groupby("Ano")["Expectativa de vida"].mean()

Ano
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: Expectativa de vida, dtype: float64

In [14]:
#tira a média de PIB
df["PIB"].mean()

np.float64(7215.327081212149)

In [ ]:
#soma de PIB
df["PIB"].sum()

np.float64(12294917.346385501)